url: https://dmoralestech.github.io/nova-cakeshop/
baseurl: /nova-cakeshop/

# Site settings
title: Awesome Cakes
email: ngcast23@yahoo.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Nova
  pic: 1
  position: Chief Baker
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Daniel
  pic: 2
  position: Lead Taster
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Sitti
  pic: 3
  position: Quality Assurance
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: facebook
    url: #
  - title: stack-overflow
    url: #
  - title: bitbucket 
    url: #
  - title: github
    url: #

# Postal address (add as many lines as necessary)
address:
  - line: Manly Vale
  - line: Manly Vale, NSW

# Build settings
markdown: kramdown
permalink: pretty